userfaultfd.c: fix mmap_sem build breaks
Fixes:-

kernel/xiaomi/sm7325/fs/userfaultfd.c:290:34: error: no member named 'mmap_sem' in 'struct mm_struct'
kernel/xiaomi/sm7325/fs/userfaultfd.c:380:37: error: no member named 'mmap_sem' in 'struct mm_struct'
kernel/xiaomi/sm7325/fs/userfaultfd.c:1352:18: error: no member named 'mmap_sem' in 'struct mm_struct'
kernel/xiaomi/sm7325/fs/userfaultfd.c:1499:16: error: no member named 'mmap_sem' in 'struct mm_struct'

Signed-off-by: kartik-commits <kartiklashkare@gmail.com>